### ISSUE TITLE
fix row splitting mechanism  

### ISSUE THREAD

**Issue by RHVDM** [MAEASaM/arches-geometry-checker#10]
Determine what causes the checker to change selected resource IDs in the input csv file when generating the output csv file. Alternatively, determine whether the checker removes selective rows from the output file.

---
In the example_valid.csv `ADMN-ZWE-0000040`, `ADMN-BWA-00000010`, `ADMN-ETH-0000006-8` is missing, while it was present in the example.csv

**Comment by razekmh** [comment]
Turns out to be a data error. Code does not require editing
