### ISSUE TITLE
add simplify functionality to the geometry checker

### ISSUE THREAD

**Issue by razekmh** [MAEASaM/arches-geometry-checker#4]

**Comment by razekmh** [comment]
@RHVDM wrote some code to simplify polygons using `shapely`  we need to integrate this code into the current tool and modify the parser to accept different options of ( only subdivide, only simplify, both)

**Comment by razekmh** [comment]
@RHVDM the [simplify function used in the code is part of the Geopandas library](https://github.com/geopandas/geopandas/blob/e3183bca193ac52f70b159baa3bc11edd871d886/geopandas/base.py#L3753). Installing this library within the QGGIS environment results in conflicts 
```
Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpi6sqdtca_in_process.py get_requires_for_build_wheel /tmp/tmpd76bfbad
       cwd: /tmp/pip-install-0nj0hqvk/fiona_b3aaccaf59c0468ca07ed5b7d69afd38
  Complete output (3 lines):
  <string>:86: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  WARNING:root:Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
  CRITICAL:root:A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
```
There is a [simplify function avaiable within QGIS python API](https://qgis.org/pyqgis/3.4/core/QgsSimplifyMethod.html#module-QgsSimplifyMethod). I suspect it might be using the same underlying method, but I think we should check the results anyway.

**Comment by razekmh** [comment]
On a closer look, the code you submitted used `gdf.simplify(tolerance, preserve_topology=True)`. Note the `preserve_topology` there.  I think since using [QgsTopologyPreservingSimplifier](https://qgis.org/pyqgis/3.4/core/QgsTopologyPreservingSimplifier.html) might be a good solution. If we want later to NOT preserve the topology, maybe we could add a different method or option. For now I think `QgsTopologyPreservingSimplifier` would be sufficient.

**Comment by RHVDM** [comment]
I am not sure how each of the systems is designed and what libraries they use ( I know they are both based on the Douglas-Peucker algorithm). However, from my experimentation with simplifying the geometry of the same polygon, I know that the results are identical. I think using the QGIS tools will be better overall, as the docker you created runs through QGIS, it doesn't make sense to use other functionalities if QGIS has the same and it does what is needed. We can later add a functionality if the topology should not be preserved, but at the moment I can't think of a scenario in which that will be required.
